export const FETCH_PODCASTS = 'FETCH_PODCASTS';
export const PODCASTS_SET_RESULT = "PODCASTS_SET_RESULT";
export const PODCASTS_LOADING = "PODCASTS_LOADING";
export const GET_PODCAST_SUCCESS = "GET_PODCAST_SUCCESS";

