export const FETCH_EPISODES = 'FETCH_EPISODES';
export const EPISODES_SET_RESULT = "EPISODES_SET_RESULT";
export const EPISODES_LOADING = "EPISODES_LOADING";
export const GET_EPISODE_SUCCESS = "GET_EPISODE_SUCCESS";

